"""Loopback recall auth token.

The HTTP endpoint binds to 127.0.0.1, which every local UNIX account can
reach - unlike the vault directory, which file permissions scope to one
user. The token closes that gap: generated by the watcher, mode 0600, read
back by the CLI running as the same user. Neither side needs configuration.

Enforcement is graced: requests without a valid token are served with a
logged warning until METALMIND_RECALL_REQUIRE_TOKEN=1 (or a later release
flips the default), so an updated watcher never breaks an older CLI.
"""
from __future__ import annotations

import hmac
import os
import secrets
from pathlib import Path

HEADER = "X-Metalmind-Token"


def token_path() -> Path:
    raw = os.environ.get("METALMIND_RECALL_TOKEN_PATH")
    if raw:
        return Path(raw).expanduser()
    return Path.home() / ".metalmind" / "recall-token"


def ensure_token() -> str:
    path = token_path()
    if path.exists():
        existing = path.read_text(encoding="utf-8").strip()
        if existing:
            return existing
    path.parent.mkdir(parents=True, exist_ok=True)
    token = secrets.token_hex(32)
    fd = os.open(str(path), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write(token + "\n")
    return token


def is_valid(supplied: str) -> bool:
    path = token_path()
    if not path.exists():
        return False
    expected = path.read_text(encoding="utf-8").strip()
    if not expected:
        return False
    return hmac.compare_digest(supplied.strip(), expected)


def enforcement_enabled() -> bool:
    return os.environ.get("METALMIND_RECALL_REQUIRE_TOKEN") == "1"
